import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Sidebar from "@/components/Sidebar";
import { ToastProvider } from "@/components/ui/Toast";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex h-full bg-gray-50 dark:bg-[#0a0a0a] text-gray-900 dark:text-gray-100">
        <ToastProvider>
          <Sidebar />
          <main className="flex-1 h-screen overflow-auto bg-white dark:bg-[#0a0a0a]">
            {children}
          </main>
        </ToastProvider>
      </body>
    </html>
  );
}
